import type { Card } from './types';

/**
 * Fallback German vocabulary — used when the database is not
 * available (local development without a Postgres connection).
 */
export const FALLBACK_CARDS: Card[] = [
    { k: 'der Tisch', h: '/tɪʃ/', v: 'cái bàn', t: 'Danh từ', ej: 'Der Tisch ist groß.', ev: 'Cái bàn lớn.', tip: 'tisch ~ table' },
    { k: 'die Katze', h: '/ˈkatsə/', v: 'con mèo', t: 'Danh từ', ej: 'Die Katze schläft.', ev: 'Con mèo ngủ.', tip: 'cat ~ Katze' },
    { k: 'das Buch', h: '/buːx/', v: 'quyển sách', t: 'Danh từ', ej: 'Das Buch ist interessant.', ev: 'Quyển sách thú vị.', tip: 'book ~ Buch' },
    { k: 'der Hund', h: '/hʊnt/', v: 'con chó', t: 'Danh từ', ej: 'Der Hund bellt.', ev: 'Con chó sủa.', tip: 'hound ~ Hund' },
    { k: 'die Schule', h: '/ˈʃuːlə/', v: 'trường học', t: 'Danh từ', ej: 'Die Schule beginnt um 8 Uhr.', ev: 'Trường bắt đầu lúc 8 giờ.', tip: 'school ~ Schule' },
    { k: 'das Haus', h: '/haʊ̯s/', v: 'ngôi nhà', t: 'Danh từ', ej: 'Das Haus ist alt.', ev: 'Ngôi nhà cũ.', tip: 'house ~ Haus' },
    { k: 'der Stuhl', h: '/ʃtuːl/', v: 'cái ghế', t: 'Danh từ', ej: 'Der Stuhl ist bequem.', ev: 'Cái ghế thoải mái.', tip: 'stool ~ Stuhl' },
    { k: 'die Blume', h: '/ˈbluːmə/', v: 'bông hoa', t: 'Danh từ', ej: 'Die Blume ist schön.', ev: 'Bông hoa đẹp.', tip: 'bloom ~ Blume' },
    { k: 'das Wasser', h: '/ˈvasɐ/', v: 'nước', t: 'Danh từ', ej: 'Das Wasser ist kalt.', ev: 'Nước lạnh.', tip: 'water ~ Wasser' },
    { k: 'der Apfel', h: '/ˈapfəl/', v: 'quả táo', t: 'Danh từ', ej: 'Der Apfel ist rot.', ev: 'Quả táo màu đỏ.', tip: 'apple ~ Apfel' },
    { k: 'gehen', h: '/ˈɡeːən/', v: 'đi', t: 'Động từ', ej: 'Ich gehe nach Hause.', ev: 'Tôi đi về nhà.', tip: 'go ~ gehen' },
    { k: 'essen', h: '/ˈɛsn̩/', v: 'ăn', t: 'Động từ', ej: 'Wir essen zusammen.', ev: 'Chúng tôi ăn cùng nhau.', tip: 'eat ~ essen' },
    { k: 'trinken', h: '/ˈtʁɪŋkn̩/', v: 'uống', t: 'Động từ', ej: 'Er trinkt Kaffee.', ev: 'Anh ấy uống cà phê.', tip: 'drink ~ trinken' },
    { k: 'schlafen', h: '/ˈʃlaːfn̩/', v: 'ngủ', t: 'Động từ', ej: 'Das Kind schläft.', ev: 'Đứa trẻ ngủ.', tip: 'sleep ~ schlafen' },
    { k: 'lernen', h: '/ˈlɛʁnən/', v: 'học', t: 'Động từ', ej: 'Ich lerne Deutsch.', ev: 'Tôi học tiếng Đức.', tip: 'learn ~ lernen' },
    { k: 'schön', h: '/ʃøːn/', v: 'đẹp', t: 'Tính từ', ej: 'Das Wetter ist schön.', ev: 'Thời tiết đẹp.', tip: '' },
    { k: 'groß', h: '/ɡʁoːs/', v: 'lớn, to', t: 'Tính từ', ej: 'Die Stadt ist groß.', ev: 'Thành phố lớn.', tip: 'gross ~ groß' },
    { k: 'klein', h: '/klaɪ̯n/', v: 'nhỏ, bé', t: 'Tính từ', ej: 'Das Kind ist klein.', ev: 'Đứa trẻ nhỏ.', tip: '' },
    { k: 'gut', h: '/ɡuːt/', v: 'tốt, giỏi', t: 'Tính từ', ej: 'Das Essen ist gut.', ev: 'Đồ ăn ngon.', tip: 'good ~ gut' },
    { k: 'schnell', h: '/ʃnɛl/', v: 'nhanh', t: 'Phó từ', ej: 'Er läuft schnell.', ev: 'Anh ấy chạy nhanh.', tip: '' },
    { k: 'die Milch', h: '/mɪlç/', v: 'sữa', t: 'Danh từ', ej: 'Die Milch ist frisch.', ev: 'Sữa tươi.', tip: 'milk ~ Milch' },
    { k: 'der Bruder', h: '/ˈbʁuːdɐ/', v: 'anh/em trai', t: 'Danh từ', ej: 'Mein Bruder ist jung.', ev: 'Anh trai tôi trẻ.', tip: 'brother ~ Bruder' },
    { k: 'die Schwester', h: '/ˈʃvɛstɐ/', v: 'chị/em gái', t: 'Danh từ', ej: 'Meine Schwester liest.', ev: 'Chị gái tôi đọc sách.', tip: 'sister ~ Schwester' },
    { k: 'lesen', h: '/ˈleːzn̩/', v: 'đọc', t: 'Động từ', ej: 'Ich lese ein Buch.', ev: 'Tôi đọc một cuốn sách.', tip: '' },
    { k: 'schreiben', h: '/ˈʃʁaɪ̯bn̩/', v: 'viết', t: 'Động từ', ej: 'Sie schreibt einen Brief.', ev: 'Cô ấy viết một bức thư.', tip: 'scribe ~ schreiben' },
    { k: 'sprechen', h: '/ˈʃpʁɛçn̩/', v: 'nói', t: 'Động từ', ej: 'Er spricht Deutsch.', ev: 'Anh ấy nói tiếng Đức.', tip: 'speak ~ sprechen' },
    { k: 'kalt', h: '/kalt/', v: 'lạnh', t: 'Tính từ', ej: 'Der Winter ist kalt.', ev: 'Mùa đông lạnh.', tip: 'cold ~ kalt' },
    { k: 'warm', h: '/vaʁm/', v: 'ấm', t: 'Tính từ', ej: 'Der Sommer ist warm.', ev: 'Mùa hè ấm.', tip: 'warm ~ warm' },
    { k: 'das Auto', h: '/ˈaʊ̯to/', v: 'ô tô, xe hơi', t: 'Danh từ', ej: 'Das Auto ist neu.', ev: 'Ô tô mới.', tip: 'auto ~ Auto' },
    { k: 'die Straße', h: '/ˈʃtʁaːsə/', v: 'con đường', t: 'Danh từ', ej: 'Die Straße ist lang.', ev: 'Con đường dài.', tip: 'street ~ Straße' },
    { k: 'arbeiten', h: '/ˈaʁbaɪ̯tn̩/', v: 'làm việc', t: 'Động từ', ej: 'Ich arbeite jeden Tag.', ev: 'Tôi làm việc mỗi ngày.', tip: '' },
    { k: 'kaufen', h: '/ˈkaʊ̯fn̩/', v: 'mua', t: 'Động từ', ej: 'Sie kauft Brot.', ev: 'Cô ấy mua bánh mì.', tip: '' },
    { k: 'der Freund', h: '/fʁɔɪ̯nt/', v: 'bạn (nam)', t: 'Danh từ', ej: 'Mein Freund kommt morgen.', ev: 'Bạn tôi đến ngày mai.', tip: 'friend ~ Freund' },
    { k: 'die Freundin', h: '/ˈfʁɔɪ̯ndɪn/', v: 'bạn (nữ)', t: 'Danh từ', ej: 'Meine Freundin ist nett.', ev: 'Bạn gái tôi tốt bụng.', tip: '' },
    { k: 'heute', h: '/ˈhɔɪ̯tə/', v: 'hôm nay', t: 'Phó từ', ej: 'Heute ist Montag.', ev: 'Hôm nay là thứ Hai.', tip: '' },
    { k: 'morgen', h: '/ˈmɔʁɡn̩/', v: 'ngày mai', t: 'Phó từ', ej: 'Morgen gehe ich einkaufen.', ev: 'Ngày mai tôi đi mua sắm.', tip: 'morning ~ morgen' },
    { k: 'die Küche', h: '/ˈkʏçə/', v: 'nhà bếp', t: 'Danh từ', ej: 'Die Küche ist sauber.', ev: 'Nhà bếp sạch sẽ.', tip: 'kitchen ~ Küche' },
    { k: 'kochen', h: '/ˈkɔxn̩/', v: 'nấu ăn', t: 'Động từ', ej: 'Meine Mutter kocht.', ev: 'Mẹ tôi nấu ăn.', tip: 'cook ~ kochen' },
    { k: 'der Garten', h: '/ˈɡaʁtn̩/', v: 'khu vườn', t: 'Danh từ', ej: 'Der Garten ist grün.', ev: 'Khu vườn xanh.', tip: 'garden ~ Garten' },
    { k: 'spielen', h: '/ˈʃpiːlən/', v: 'chơi', t: 'Động từ', ej: 'Die Kinder spielen draußen.', ev: 'Bọn trẻ chơi ngoài trời.', tip: '' },
    { k: 'der Lehrer', h: '/ˈleːʁɐ/', v: 'thầy giáo', t: 'Danh từ', ej: 'Der Lehrer erklärt die Aufgabe.', ev: 'Thầy giáo giải thích bài tập.', tip: '' },
    { k: 'die Lehrerin', h: '/ˈleːʁəʁɪn/', v: 'cô giáo', t: 'Danh từ', ej: 'Die Lehrerin ist freundlich.', ev: 'Cô giáo thân thiện.', tip: '' },
    { k: 'alt', h: '/alt/', v: 'già, cũ', t: 'Tính từ', ej: 'Das Gebäude ist alt.', ev: 'Tòa nhà cũ.', tip: 'old ~ alt' },
    { k: 'neu', h: '/nɔɪ̯/', v: 'mới', t: 'Tính từ', ej: 'Ich habe ein neues Handy.', ev: 'Tôi có một điện thoại mới.', tip: 'new ~ neu' },
    { k: 'und', h: '/ʊnt/', v: 'và', t: 'Liên từ', ej: 'Ich und du.', ev: 'Tôi và bạn.', tip: 'and ~ und' },
    { k: 'aber', h: '/ˈaːbɐ/', v: 'nhưng', t: 'Liên từ', ej: 'Ich bin müde, aber glücklich.', ev: 'Tôi mệt nhưng hạnh phúc.', tip: '' },
    { k: 'mit', h: '/mɪt/', v: 'với', t: 'Giới từ', ej: 'Ich gehe mit dir.', ev: 'Tôi đi với bạn.', tip: '' },
    { k: 'in', h: '/ɪn/', v: 'trong, ở trong', t: 'Giới từ', ej: 'Ich bin in der Schule.', ev: 'Tôi ở trong trường.', tip: 'in ~ in' },
    { k: 'auf', h: '/aʊ̯f/', v: 'trên', t: 'Giới từ', ej: 'Das Buch liegt auf dem Tisch.', ev: 'Quyển sách nằm trên bàn.', tip: '' },
    { k: 'langsam', h: '/ˈlaŋzaːm/', v: 'chậm', t: 'Phó từ', ej: 'Er fährt langsam.', ev: 'Anh ấy lái xe chậm.', tip: '' },
];
